---
layout: single
title: (Java) 학원수업20220516
categories: academy
# git, study, diary, java, toDolist, cooking, plan, html, academy
tag: [academy] 
---


# 책진도_10 예외

예외는 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류를 말한다. 예외가 발생하면 프로그램이 곧바로 종료된다는 점에서 에러와 동일하지만, 예외처리를 통해 정상 실행상태를 유지할 수 있다.


일반예외(Exception) : 컴파일러 체크 예외. 컴파일러가 예외처리 필요한지 검사하고, 만약 없다면 예외처리코드가 없다면 컴파일 오류 발생. 
 
실행예외(Runtime Exception) : 컴파일 과정에서 예외처리코드를 검사하지 않는 예외.

## 10.2 실행예외

자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외처리코드를 삽입해야 한다.

### 10.2.1 NullPointException

Null값을 갖는 객체를 사용하려 할때 발생하는 예외.

~~~java
public class NullPointExceptionExample {

	public static void main(String[] args) {
		String data = null;
		System.out.println(data.toString());
	}
}
~~~

~~~
Exception in thread "main" java.lang.NumberFormatException: For input string: "a100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at ch10.NumberFormatExceptionExample.main(NumberFormatExceptionExample.java:10)
~~~

### 10.2.2 ArrayIndexOutOfBoundsException

배열에서 인덱스 범위를 초과하여 사용할 경우 발생하는 예외.

~~~java
public class ArrayIndexOutOfBoundsExceptionExample {

	public static void main(String[] args) {
		if(args.length == 2) {
			
		String data1 = args[0];
		String data2 = args[1];
		
		System.out.println("args[0] : "+data1);
		System.out.println("args[1] : "+data2);
		} else {
			System.out.println("[실행방법]");
			System.out.println("java ArrayIndexOutOfBoundsExceptionExample ");
			System.out.println("값1 값2");
		}
	}
}
~~~

### 10.2.3 NumberFormatException

parseInt(), parseDouble() 메서드로 문자열로 되어있는 데이터를 숫자로 변경할 때, 숫자로 변환될 수 없는 문자가 포함되어 있다면 발생하는 예외

~~~java
public class NumberFormatExceptionExample {

	public static void main(String[] args) {
		String data1 = "100";
		String data2 = "a100";
		
		int value1 = Integer.parseInt(data1);
		int value2 = Integer.parseInt(data2); // NumberFormatException 발생
		
		int result = value1 + value2;
		System.out.println(data1 + "+" + data2 + "=" + result );
	}
}
~~~

~~~
Exception in thread "main" java.lang.NumberFormatException: For input string: "a100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at ch10.NumberFormatExceptionExample.main(NumberFormatExceptionExample.java:10)
~~~

### 10.2.4 ClassCastException

타입변환(casting)은 상위 클래스와 하위 클래스 간에 발생하고
구현 클래스와 인터페이스 간에도 발생한다.
이러한 관계가 아니라면 클래스는 다른 클래스로 타입 변환할 수 없다.

~~~java
public class ClassCastException {

	public static void main(String[] args) {
		Dog dog = new Dog();
		changeDog(dog);
		
		Cat cat = new Cat();
		changeDog(cat); // Cat객체를 매개값으로 줌
	}
	public static void changeDog (Animal animal) {
		if(animal instanceof Dog) {
			Dog dog = (Dog) animal; // ClassCastException 발생 가능
		}
	}
}
class Animal {}
class Dog extends Animal {}
class Cat extends Animal {}
~~~

## 10.3 예외 처리 코드

예외가 발생했을 경우, 프로그램의 갑작스러운 종료를 막고 정상 실행을 유지할 수 있도록 처리하는 코드를 예외 처리 코드라고 말한다.

자바 컴파일러는 일반예외가 발생할 가능성이 있는 코드를 발견하면 컴파일을 오류를 발생시켜 개발자로 하여금 예외 처리 코드를 작성하도록 요구한다.

실행예외는 컴파일러가 체크해주지 않기 때문에 개발자의 경험을 바탕으로 작성해야 한다. 

예외처리코드는 try-catch-finally 블록을 이용한다.

~~~java
try {
    예외 발생 가능 코드
} catch (예외클래스 e) {
    예외 처리
} finally { // 생략 가능
    항상 실행;
}
~~~

~~~java
// 일반예외처리
public class TryCatchFinallyExample {
	public static void main(String[] args) {
		try {
			Class clazz = Class.forName("java.lang.String2");
		} catch (ClassNotFoundException e) {
			System.out.println("클래스가 존재하지 않습니다.");
		}
	}
}
~~~

~~~java
// 실행예외처리
public class TrycatchFinallyRuntimeExceptionExample {
	public static void main(String[] args) {
		String data1 = null;
		String data2 = null;
		
		try {
			data1 = args[0];
			data2 = args[1];
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
			System.out.println("[실행 방법]");
			System.out.println("java TryCatchFinallyRuntimeExceptionExample num1 num2");
			return; // 메서드 종료
		}
		
		try {
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			System.out.println(data1 + "+" + data2 + "=" + result);
		} catch (NumberFormatException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} finally {
			System.out.println("다시 실행하세요");
		}
	}
}
~~~

## 10.4 예외 종류에 따른 처리 코드

### 10.4.1 다중 catch

try블록 내부는 다양한 종류의 예외가 발생할 수 있다. 발생되는 예외별로 예외 처리 코드를 다르게 하려면 다중 catch블록을 작성하면 된다.
catch블록이 여러개라도 단 하나의 catch블록만 실행된다.

~~~java
public class CatchByExceptionKindExample {

	public static void main(String[] args) {
		try {
			String data1 = args[0];
			String data2 = args[1];
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			System.out.println(data1 + "+" + data2 + "=" + result);
		} catch ( ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
			System.out.println("[실행 방법]");
			System.out.println("java CatchByExceptionKindExample num1 num2");
		} catch ( NumberFormatException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
~~~


### 10.4.2 catch 순서

상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야한다.
하위 예외는 상위 예외를 상속했기때문에 상위 예외가 위에 있다면 상위예외만 선택되어 실행된다.

~~~java
try {
    ArrayIndexOutOfBoundsEsception 발생

    NumberFormatException 발생
} catch (Exception e) {
    에외 처리 1

// 상위예외가 위에있어서 실행되지 못함
} catch (ArrayIndexOutOfBoundsException e) { 
    예외 처리 2 
}
~~~

~~~java
public class CatchOrderExample {

	public static void main(String[] args) {
		try {
			String data1 = args[0];
			String data2 = args[1];
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			System.out.println(data1 + "+" + data2 + "=" + result);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
		} catch (Exception e) {
			System.out.println("실행에 문제가 있습니다.");
		} finally {
			System.out.println("다시 실행하세요");
		}
	}
}
~~~

### 10.4.3 멀티 catch

catch()괄호 안에 |로 연결하여 하나의 catch블록에서 여러개의 예외를 동일하게 처리할 수 있다.

~~~java
public class MultiCatchExample {

	public static void main(String[] args) {
		try {
			String data1 = args[0];
			String data2 = args[1];
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			System.out.println(data1 + "+" + data2 + "=" + result);
		} catch (ArrayIndexOutOfBoundsException | NumberFormatException e) {
			System.out.println("실행 매개값의 수가 부족하거나 숫자로 변환할 수 없습니다.");
		} catch (Exception e) {
			System.out.println("알 수 없는 예외 발생");
		} finally {
			System.out.println("다시 실행하세요");
		}
	}
}
~~~